packages:
  - '*/src'

catalogs:
  icons:
    '@iconify-json/carbon': ^1.2.8
    '@iconify-json/devicon': ^1.2.23
    '@iconify-json/logos': ^1.2.4
    '@iconify-json/simple-icons': ^1.2.31
    '@iconify-json/solar': ^1.2.2
    '@iconify/utils': ^3.0.0
    '@proj-airi/lobe-icons': ^1.0.10

onlyBuiltDependencies:
  - esbuild
  - playwright-chromium
